### PR TITLE
Improving general moderation

### PR DESCRIPTION
**Pull request by MambaDev**
### Overview
Users endpoint now supports improved paging to search through users. With the change to also return a array of connection information.  e.g connected to twitch with username. 

#### User Deletion
When deleting a user, we keep the ids the same for the editor and index on the player object. Only setting the internal Id to null. This allow the front end to be able to handle multiple deleted users while also showing which user had which editor (removed or not).

#### Game Application requests
When requesting game applications for a specified game and or schedule, profile and or stats boolean can be used in the query to ensure that they are also returned with the users.

### Notes
 * When requesting a game and specifying that you want players, connections will be included.
 * game patches update meta and teams

### CODE REVIEW

**Comment by SYNTAG** [comment]
@MambaDev The only bug I was able to find was when you delete a user it won't replace them as Competitor if they were on the red team.

**Comment by MambaDev** [comment]
@SYNTAG That does not make much sense since it will work regardless. You must ensure you are testing with actual self created game data, since the seeded data is not done correctly and thus is not in the actual expected format as if it was created via the api.

here is a example of deletion of multiple users on multiple teams (https://i.imgur.com/gTmjHtY.mp4). You cannot also delete users who are of moderator or higher, they first must be demoted.

**Comment by SYNTAG** [comment]
> @SYNTAG That does not make much sense since it will work regardless. You must ensure you are testing with actual self created game data, since the seeded data is not done correctly and thus is not in the actual expected format as if it was created via the api.
> 
> here is a example of deletion of multiple users on multiple teams (https://i.imgur.com/gTmjHtY.mp4). You cannot also delete users who are of moderator or higher, they first must be demoted.
> 
> Additionally testing on the user who wanted there account removed prior will not work since self database modification has put that users data in a inconsistent format and thus cannot be deleted without reversing the changes.

Sorry, I realized I should've been more specific. I am testing with real data and deleting a standard user (non-moderator) role. Deleting does work on the red team if you delete a user from it initially, however, the bug I encountered seems to only happen if the same user played on the red team from another game.

Here is a video example of deletion bug I found last night:
https://i.imgur.com/MFXpNNc.gif

I did more testing today and found that it might not be as clear cut as I thought to reproduce. Because in the case of `Rascal_Two`. It did remove him from 2 games (blue and red), but not from the third game. See example footage below:
https://i.imgur.com/uxEGKvL.gif

**Comment by SYNTAG** [comment]
@MambaDev 

> @SYNTAG That does not make much sense since it will work regardless. You must ensure you are testing with actual self created game data, since the seeded data is not done correctly and thus is not in the actual expected format as if it was created via the api.
> 
> here is a example of deletion of multiple users on multiple teams (https://i.imgur.com/gTmjHtY.mp4). You cannot also delete users who are of moderator or higher, they first must be demoted.
> 
> Additionally testing on the user who wanted there account removed prior will not work since self database modification has put that users data in a inconsistent format and thus cannot be deleted without reversing the changes.

Sorry, I realized I should've been more specific. I am testing with real data and deleting a standard user (non-moderator) role. Deleting does work on the red team if you delete a user from it initially, however, the bug I encountered seems to only happen if the same user played on the red team from another game.

Here is a video example of deletion bug I found last night:
https://i.imgur.com/MFXpNNc.gif

I did more testing today and found that it might not be as clear cut as I thought to reproduce. Because in the case of `Rascal_Two`. It did remove him from 2 games (blue and red), but not from the third game. See example footage below:
https://i.imgur.com/uxEGKvL.gif

**Comment by MambaDev** [comment]
@SYNTAG The concern is that the older applications don't exist for that given user in the database.

e.g is grabs existing game applications, iterates the players, if they exist by id, does a localised replacement, we could extend this to also do a direct match on username as well. But ideally  I would rather it be in a better database state in which we don't have to crawl through nested xml just to confirm placements. Maybe for scores, results and such but for player allocation, this could be better.

**Comment by SYNTAG** [comment]
@MambaDev Can we iterate through the games instead of the game applications. This way we can make sure to replace each user in the game storage.

Game applications aren't that reliable since we can't guarantee that the user will exist on the application. For example, adding players through the mod panel (or the new editor) or switching players during a live game.

**Comment by MambaDev** [comment]
@SYNTAG game applications are the only direct relation to the game which stores that kind of information. Iterating through all games to find the users being deleted is just a hack and does not scale.

Its avoiding the actual issue which is the lack of concrete information relating the users to the game.  It should be designed to correctly allow updating, removing or adding/removing roles to users. Iterating all games is more of a hack and all platforms should use the api to perform actions.

**Comment by SYNTAG** [comment]
@MambaDev I understand that Game Applications has a direct relation to the game, but that doesn't inherently mean they are more reliable. And especially in this case, where there was that disconnect preventing the rest of the user from being completely removed from each game. The examples I gave above are also real cases that have happened before (switching user during game/adding them via mod panel). 

Since the user relations do exist in the game storage, I would argue that iterating through the games would not be a hack since we would be referencing the final data from the game provided by the editor.

**Comment by MambaDev** [comment]
@SYNTAG you cannot interative through every single game to just check if the user was assigned its not practical and does not scale. There needs to be improved implementation of the relationship and assigning, removing or updating should go thorugh applications.

**Comment by SYNTAG** [comment]
@MambaDev I think we are arguing about two different things here. We need to have a separate discussion about the database structure if you would like to revisit that. But my goal right now is to address the issue on this commit so we can merge this branch into production. The issue is the user deletion is not fully cleansing the user out of all the games they've played in. I just want to avoid having bad data in the Games storage if we can.

**Comment by MambaDev** [comment]
@SYNTAG The problem is how the data is being stored  and updated as its not consistant. There is no real way of doing a query on the games without the awful json based querying which is not worth investing time into.

**Comment by MambaDev** [comment]
@SYNTAG we can do all games query a funky query for the time being but it should not be the defaulto in the future.

**Comment by SYNTAG** [comment]
@MambaDev Ok that works for me. And sounds good, let's link up some time to chat more about it.

**Comment by MambaDev** [comment]
@SYNTAG try now => npm install since its been rebased with master.

**Pull request merged**
